config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  get 'instruction', to: 'dashboard#instruction'
  %w(administrator university_manager expert participant).each do |key|
    namespace(key) { root to: 'spa#index' }
  end
  resource :users, only: [] do
    collection do
      get :search
    end
  end
  resources :contests do
    get 'generate_rate_list'
    get 'generate_protocol'
    resources :nominations
    resources :criterions
    resources :participants do
      collection do
        get :by_nomination
        get :by_nomination_results
        get :for_results
      end
    end
    resources :marks, only: [:index] do
      member do
        get :history
      end
    end
    resources :experts do
      collection do
        get :for_results
      end
      resources :marks, only: [:create, :update] do
        collection do
          get :by_participant
        end
      end
    end
  end

  resources :permissions, only: [:index, :create, :destroy] do
    collection do
      get :available_roles
    end
  end
end

app/models/criterion.rb
# == Schema Information
#
# Table name: criterions
#
#  id         :bigint           not null, primary key
#  title      :string
#  contest_id :bigint
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Criterion < ApplicationRecord
  belongs_to :contest
  has_many :marks, dependent: :destroy
  validates :title, :contest, presence: true
end

app/controllers/criterions_controller.rb
class CriterionsController < ApplicationController
  load_and_authorize_resource

  def index
    @contest = Contest.find(params[:contest_id])
    @criterions = @contest.criterions
  end

  def create
    if @criterion.save
      render :create
    else
      render :errors
    end
  end

  def update
    if @criterion.update(criterion_params)
      render :update
    else
      render :errors
    end
  end

  def destroy
    if @criterion.destroy
      render :destroy
    else
      render :errors
    end
  end

  private
    def criterion_params
      params.require(:criterion).permit(:title, :contest_id)
    end
end

app/views/criterions/index.html.erb
<%= render partial: '/layouts/left_menu' %>
<div class='col-xs-9'>
  <h1>Критерии отбора</h1>

  <table>
    <tr>
      <th>Название</th>
      <th colspan="2"></th>
    </tr>

    <% @criterions.each do |criterion| %>
      <tr>
        <td><%= criterion.title %></td>
        <td><%= link_to 'Изменить', edit_contest_criterion_path(criterion.contest.id, criterion) %></td>
        <td><%= link_to 'Удалить', contest_criterion_path(criterion.contest, criterion),
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>

  <%= link_to 'Добавить критерий',
    new_contest_criterion_path,
    class: 'btn btn-blue'%>
</div>